blank_issues_enabled: true
contact_links:
  - name: QQ 交流群
    url: https://www.example.org/REPLACE_THIS_LINK
    about: 群号：XXXXXXXXX
  - name: Discord Server
    url: https://www.example.org/REPLACE_THIS_LINK
    about: Invite code: XXXXXXX
